### ISSUE TITLE
Can't resume uploads!

### ISSUE THREAD

**Issue by Rux77** [tus/tus-js-client#121]
I am developing a website using **Laravel**, and I am using **tus-js-client** to upload files directly to **Vimeo** without going through my server. The uploading works perfect.

But, lets say the uploading reached 44%, and then the user refreshed the browser... as I understand It should continue uploading from 44% when the user start uploading the same file again.. but that doesn't happen!

      // Create a new tus upload
      var self = this;
      // Send request to server to get uploadUrl endpoint from Vimeo api
      var uploadEndPoint = self.getUploadEndPoint();
      // Start uploading
      self.uploader = new tus.Upload(file, {
        uploadUrl: uploadEndPoint,
        retryDelays: [0, 1000, 3000, 5000],
        metadata: {
          filename: file.name,
          filetype: file.type
        },
        resume: true,
        uploadSize: file.size,
        onError: function(error) {
          console.log("Failed because: " + error);
        },
        onProgress: function(bytesUploaded, bytesTotal) {
          var percentage = (bytesUploaded / bytesTotal * 100).toFixed(2);
          console.log(bytesUploaded, bytesTotal, percentage + "%");
        },
        onSuccess: function() {
          console.log(
            "Download %s from %s",
            self.uploader.file.name,
            self.uploader.url
          );
        }
      });

**Comment by Acconut** [comment]
> But, lets say the uploading reached 44%, and then the user refreshed the browser... as I understand It should continue uploading from 44% when the user start uploading the same file again.. but that doesn't happen!

That's how it should behave, you are right. What is happening instead?

**Comment by Rux77** [comment]
I think this is happening because when I send an API request to Vimeo to get an **uploadUrl endpoint** It will give me a new **uploadUrl endpoint** when the user refresh the page..

**Comment by Acconut** [comment]
> I think this is happening because when I send an API request to Vimeo to get an uploadUrl endpoint It will give me a new uploadUrl endpoint when the user refresh the page..

That seems to be the likely cause as far as I can tell.

**Comment by Rux77** [comment]
but isn't this the **"resume = true"** job? as I understand:

User was uploading a file then when it reached 44%, the user refreshed the page, then the user re-upload the same file again:
1 - check if the file object is stored in the storage (using fingerprint unique string).
2 - if the file is there (fingerprint) get the uploadUrl to resume the upload for the same file to the previous uploadUrl endpoint.

Is this right?

**Comment by Acconut** [comment]
> but isn't this the "resume = true" job?

Not in this case. If you supply a `uploadUrl`, tus-js-client will resume using this URL even if the file has been uploaded to some other URL before. This fact is also stated in the documentation:

> `uploadUrl = null:` a URL which will be used to directly attempt a resume **without** generating the fingerprint and looking it up before.

However, if no `uploadUrl` is given, you would be correct.

> Is there a way to check if the (fingerprint) for the file exist?

No, there is currently no way to do so.

**Comment by Rux77** [comment]
Thank you for your help, I have solved the issue using server-side cache.

**Comment by mahmudul** [comment]
Hi @Acconut, pretty same issue I am facing for couple of days. In my case, when I click on resume for a paused upload, it begins from the start. I checked the solution that 'ghost' resolved by. I am using file based cache in server-side where I have .cache/ folder having 'tus_php.server.cache' file. A sample entry looks like when I click pause: 

"tus:server:41b5c307-a9c5-406a-8a3a-a2335732ecf4":{"name":"IMG_0045.JPG","size":2078503,"offset":0,"checksum":"","location":"http:\/\/example.com\/files\/41b5c307-a9c5-406a-8a3a-a2335732ecf4","file_path":"\/var\/www\/vhosts\/example.com\/uppy\/uploads\/IMG_0045.JPG","created_at":"Sun, 21 Apr 2019 05:53:01 GMT","expires_at":"Mon, 22 Apr 2019 05:53:01 GMT","upload_type":"normal"}}

Once it is uploaded without any pause, the cache file looks like:

"tus:server:41b5c307-a9c5-406a-8a3a-a2335732ecf4":{"offset":2078503,"name":"IMG_0045.JPG","size":2078503,"checksum":"","location":"http:\/\/example.com\/files\/41b5c307-a9c5-406a-8a3a-a2335732ecf4","file_path":"\/var\/www\/vhosts\/example.com\/uppy\/uploads\/IMG_0045.JPG","created_at":"Sun, 21 Apr 2019 05:53:01 GMT","expires_at":"Mon, 22 Apr 2019 05:53:01 GMT","upload_type":"normal"}}

Only the offset has been changed. If I am missing anything on the server side cache settings. I am using tus-js-client at client side. Here is the Tus config at client:

`
    .use(Tus, {
		  endpoint: '/files/', // use your tus endpoint here
		  resume: true,
		  autoRetry: true,
		  retryDelays: [0, 1000, 3000, 5000]
		})`
Thanks in advance.

**Comment by Acconut** [comment]
@mahmudul I don't see an inherent problem with your configuration but it might be caused by tus_php, which I have never used personally. Does the problem persist if you use `https://master.tus.io/files/` (notice the trailing slash) as the endpoint? If the problem vanishes we know that is likely caused by the server and not by tus-js-client. Also what environment are you in? I would assume the browser, right?

**Comment by mahmudul** [comment]
Hi @Acconut, thanks for your reply. Yes I am using browser and `https://master.tus.io/files/` is working fine as Tus endpoint. It also works well in my local pc environment using file cache. So, it should be server side issue. I can see that the file opcache is disabled in the server and suspecting that could be the cause. Though it's not a tus-js-client issue, may I ask you whether enabling opcache could resolve the issue? I am hopeful but not sure 100%.

**Comment by Acconut** [comment]
> So, it should be server side issue.

Yes, I agree with that.

> I can see that the file opcache is disabled in the server and suspecting that could be the cause. Though it's not a tus-js-client issue, may I ask you whether enabling opcache could resolve the issue?

Frankly, I don't know. I have never used tus_php and my PHP knowledge does not include opcache. So I can't help you there and would recommend that you just give it a try.

**Comment by mahmudul** [comment]
Thanks @Acconut for your time on this. I'll have a try. I have opened an issue at [tus-php](https://github.com/ankitpokhrel/tus-php/issues/139) that I am using as tus server. May be the owner could  provide some insights. 
Cheers.

**Comment by aqib008** [comment]
Hi can we upload file direct to GCS using presigned url using this library?
